using System.Collections.Generic;
using System.Security.Policy;
using Specialist.Entities.Utils;

namespace Specialist.Entities.Catalog.Const {
	public class CourseUrls {
		public static HashSet<string> CiscoBlock = new HashSet<string>{
			"kyuos",
			"mpls",
			"mplst",
			"rskat6k",
			"sens",
			"simos",
			"sisas",
			"sitks",
			"iuvms",
			"iuvn",
			"tsse",
			"spngn1",
			"spngn2",
			"sprout",
			"spadvrout",
			"spkor",
			"spedzh",
			"dcmds",
			"cvlms",
			"arktsis-a",
			"iune",
			"dkad",
			"kuvs",
			"d7adm",
			"dcni1-a",
			"svlat",
			"cvlf",
			"cvmn-a",
			"dcnid-a",
			"rvpn",
			"ips",
			"ironp1",
			"ironp2",
			"ironp3",
			"sanas",
			"ikomm",
			"tsvois-a",
			"tsipt1-a",
			"tsipt2-a",
			"caps",
			"paet",
			"gateway",
			"voice",
			"patv1",
			"ucd",
			"uemi",
			"ucad",
"djplat11",
"jplat10",
"jplat9",
"jplat5",
"jplat6",
"djbez4",
"jroute1",
"djrout6",
"jswitch3",
"jroute2",
"jroute3",
"jbez2",
"jbez3",
"jsec8",
"jplat1",
"jplat7",
"jplat8",
"jes1",
"jes2",
"jes4",

		};


	    public static readonly HashSet<string> Print3dUrls = new HashSet<string>{
		    "3dm1-z",
		    "3dm21",
		    "3dm2-z",
		    "3dm3a-b",
		    "3dm3v-a",
		    "3dm3b-b",
		    "3dm4a",
		    "3dm4b",
		    "3dm4-a",
		    "zdm44",
		    "vrei1-a",
		    "vrei2",
		    "maya1-v",
		    "maya2",
		    "v-ray-courses",
		    "fshan",
		    "flash1-b",
		    "flash2-b",
		    "flash3",
		    "flash5",
		    "fsh3d",
		    "zbrash",
		    "cherch",
		    "akad20101",
		    "akad20102",
		    "akad20103d",
		    "revmep",
		    "3dprint",
		    "lisp",
		    "spds",
		    "as1-g",
		    "arkh1-b",
		    "arkh2-b",
		    "arts",
		    "dialuks",
		    "solv1",
		    "solv2",
		    "solv3c",
		    "solv3d",
		    "solv3l",
		    "solv3m",
		    "pdm",
		    "kosv-a",
		    "flov-a",
		    "fotv-a",
		    "inv-g",
		    "revmep",
		    "mep2010",
		    "tsivil-b",
		    "prinzh",
		    "rev2013",
		    "rinoc-a"};


	}
}