using System.Collections.Generic;
using System.Reflection;
using Microsoft.Practices.Unity;
using SimpleUtils.Common.Extensions;
using Specialist.Entities.Catalog.Interface;
using Specialist.Entities.Context;
using SimpleUtils.Collections.Extensions;
using Specialist.Services.Core.Interface;
using System.Linq;
using Specialist.Web.Common.Utils;

namespace Specialist.Web.Cms.Services {
	public class EntityService {
		 

		string GetUrl(IEntityCommonInfo entity) {
			var template = "/{0}/{1}";
			if(entity is SiteTerm)
				template = "/dictionary/definition/{1}";
			if(entity is Product)
				template += "-courses";
			return template.FormatWith(entity.GetType().Name, entity.UrlName).ToLowerInvariant();
		}
		public List<IEntityCommonInfo> GetMainEntites() {
			return CacheUtils.Get(MethodBase.GetCurrentMethod(), () => {
				var sections = Cms.MvcApplication.Container.Resolve<IRepository<Section>>()
					.GetAll(x => x.IsActive && !x.IsMain);
				var vendors = Cms.MvcApplication.Container.Resolve<IRepository<Vendor>>().GetAll(x => x.IsActive);
				var products = Cms.MvcApplication.Container.Resolve<IRepository<Product>>().GetAll(x => x.IsActive);
				var professions = Cms.MvcApplication.Container.Resolve<IRepository<Profession>>().GetAll(x => x.IsActive);
				var siteTerms = Cms.MvcApplication.Container.Resolve<IRepository<SiteTerm>>().GetAll(x => x.IsActive);
				var entities = new List<IEntityCommonInfo>();
				entities.AddRange(sections);
				entities.AddRange(products);
				entities.AddRange(vendors);
				entities.AddRange(siteTerms);
				entities.AddRange(professions);
				return entities.OrderBy(GetRank).ToList();
			});
		}
		public byte GetRank(IEntityCommonInfo entity) {
			var url = GetUrl(entity);
			var rank = PageRanks.GetValueOrDefault(url);
			if(rank == 0)
				return 5;
			return rank;
		}

		private static readonly Dictionary<string, byte> PageRanks = new Dictionary<string, byte> {
			{"/vendor/microsoft", 1},
			{"/vendor/1c", 1},
			{"/product/photoshop-courses", 1},
			{"/product/1c-predpriyatie-8-courses", 1},
			{"/product/excel-courses", 1},
			{"/vendor/cisco", 1},
			{"/vendor/unix", 1},
			{"/product/3ds-max-courses", 1},
			{"/section/buhgalter", 1},
			{"/product/office-courses", 1},
			{"/product/autocad-courses", 1},
			{"/product/windows-server-2008-courses", 1},
			{"/profession/sysadmin", 1},
			{"/section/programming", 2},
			{"/vendor/microsoft/certifications", 2},
			{"/product/sql-server-courses", 2},
			{"/profession/web-designer", 2},
			{"/section/design", 2},
			{"/product/flash-courses", 2},
			{"/vendor/oracle", 2},
			{"/profession/programmer", 2},
			{"/product/windows-7-courses", 2},
			{"/vendor/adobe", 2},
			{"/section/web", 2},
			{"/section/buhgalterskie-kursy", 2},
			{"/section/user", 2},
			{"/section/soul", 2},
			{"/product/marshrutizatori_kommutatori_cisco-courses", 2},
			{"/section/hr-management", 2},
			{"/profession/html-coder", 2},
			{"/product/1c-buhgalteriya-courses", 2},
			{"/vendor/autodesk", 2},
			{"/section/network", 2},
			{"/profession/1c-programmer", 2},
			{"/product/1c-zarplata-i-upravlenie-personalom-8-courses", 2},
			{"/product/visual-studio-2010-courses", 2},
			{"/product/illustrator-courses", 2},
			{"/section/web-design", 2},
			{"/section/web-programming", 2},
			{"/vendor/pmi", 2},
			{"/section/project-management", 2},
			{"/section/1c-programming", 2},
			{"/product/indesign-courses", 2},
			{"/section/programmer-beginner", 2},
			{"/product/linux-courses", 2},
			{"/section/design-essentials", 2},
			{"/profession/verstalschik", 2},
			{"/section/user-beginner", 2},
			{"/profession/accounter", 2},
			{"/profession/pc-technican", 2},
			{"/product/project-courses", 2},
			{"/product/mysql-courses", 2},
			{"/section/management", 2},
			{"/dictionary/definition/php", 2},
			{"/vendor/microsoft/testing/1", 2},
			{"/product/1c-buhgalteriya-8-courses", 2},
			{"/section/it-systems-management", 2},
			{"/profession/seo", 2},
			{"/product/access-courses", 2},
			{"/profession/sales-manager", 2},
			{"/product/archicad-courses", 2},
			{"/product/ege-math-courses", 2},
			{"/section/logistic", 2},
			{"/product/windows-sever-2003-courses", 2},
			{"/section/smeta", 2},
			{"/section/cg", 2},
			{"/product/sql-server-2008-courses", 2},
			{"/profession/dba", 2},
			{"/section/english", 2},
			{"/section/english-common", 2},
			{"/product/1c-upravlenie-torgovley-8-courses", 2},
			{"/section/kadr", 2},
			{"/vendor/solidworks", 2},
			{"/section/3d-design", 2},
			{"/section/photo", 2},
			{"/section/web-marketing-seo", 2},
			{"/product/windows-server-courses", 2},
			{"/section/ege", 2},
			{"/section/web-beginner", 2},
			{"/section/computer-repair", 2},
			{"/vendor/google", 2},
			{"/profession/marketing-manager", 2},
			{"/section/cad", 2},
			{"/section/hr", 2},
			{"/section/os-administration", 2},
			{"/section/database", 2},
			{"/product/moss-courses", 2},
			{"/profession/smetchik", 2},
			{"/profession/3d-animator", 2},
			{"/profession/hr", 2},
			{"/section/dtp", 2},
			{"/product/system-center-courses", 2},
			{"/section/information-security", 2},
			{"/section/computer-service", 2},
			{"/vendor/kaspersky", 2},
			{"/profession/computer-operator", 2},
			{"/dictionary/definition/ceh", 2},
			{"/section/marketing", 2},
			{"/section/business", 2},
			{"/product/visual-studio-2008-courses", 2},
			{"/profession/cad-designer", 2},
			{"/dictionary/definition/msfo", 2},
			{"/product/ege-russkiy-yazyk-courses", 2},
			{"/product/solidworks-courses", 2},
			{"/section/school", 2},
			{"/product/exchange-server-2010-courses", 2},
			{"/product/joomla-courses", 2},
			{"/product/oracle11g-courses", 2},
			{"/section/advanced-user-courses", 2},
			{"/product/coreldraw-courses", 2},
			{"/section/master-class", 2},
			{"/section/video", 2},
			{"/section/network-basics", 2},
			{"/product/exchange-server-courses", 2},
			{"/section/microsoft-programming", 2},
			{"/section/office-management", 2},
			{"/dictionary/definition/virtualization", 2},
			{"/product/after-effects-courses", 2},
			{"/product/windows-courses", 2},
			{"/product/1c-predpriyatie-77-courses", 2},
			{"/section/finance", 2},
			{"/profession/web-programmer", 2},
			{"/profession/web-programmer-php", 2},
			{"/dictionary/definition/java", 2},
			{"/dictionary/definition/itil", 2},
			{"/section/nalog", 2},
			{"/product/1c-torgovlya-i-sklad-77-courses", 2},
			{"/profession/logist", 2},
			{"/section/director", 2},
			{"/dictionary/definition/javascript", 2},
			{"/product/ege-obschestvoznanie-courses", 2},
			{"/product/powerpoint-courses", 2},
			{"/section/cms", 3},
			{"/product/word-courses", 3},
			{"/section/it-management", 3},
			{"/product/v-ray-courses", 3},
			{"/dictionary/definition/security-common", 3},
			{"/profession/photo-designer", 3},
			{"/product/premiere-pro-courses", 3},
			{"/vendor/1c/certifications", 3},
			{"/product/sharepoint-courses", 3},
			{"/section/network-administration", 3},
			{"/section/server-administration", 3},
			{"/section/qa", 3},
			{"/vendor/d-link", 3},
			{"/dictionary/definition/html", 3},
			{"/section/english-it", 3},
			{"/product/ege-phisics-courses", 3},
			{"/product/ip-communication_cisco-courses", 3},
			{"/section/free-software-courses", 3},
			{"/section/gia", 3},
			{"/product/maya-courses", 3},
			{"/product/delphi-courses", 3},
			{"/dictionary/definition/python", 3},
			{"/section/school-10-11", 3},
			{"/section/toefl", 3},
			{"/profession/interier-designer", 3},
			{"/section/all", 3},
			{"/section/school-5-9", 3},
			{"/product/kompas-3d-courses", 3},
			{"/dictionary/definition/italy-photo", 3},
			{"/vendor/cisco/certifications", 3},
			{"/section/helpdesk", 3},
			{"/section/english-business", 3},
			{"/product/network_security_cisco-courses", 3},
			{"/profession/designer", 3},
			{"/product/network_design_cisco-courses", 3},
			{"/section/drawing", 3},
			{"/profession/java-programmer", 3},
			{"/profession/security-specialist", 3},
			{"/section/buch-seminar", 3},
			{"/profession/content-manager", 3},
			{"/vendor/ec-council", 3},
			{"/dictionary/definition/asp-dot-net", 3},
			{"/profession/system-engineer", 3},
			{"/product/ege-inform-courses", 3},
			{"/product/ege-russkiy-yazyk", 3},
			{"/section/english-engineer", 3},
			{"/section/net", 3},
			{"/certification/1c-professional", 3},
			{"/product/practical_technology_cisco-courses", 3},
			{"/section/programmer-school", 3},
			{"/profession/qa-specialist", 3},
			{"/section/kadr-seminar", 3},
			{"/product/ege-history-courses", 3},
			{"/product/inventor-courses", 3},
			{"/dictionary/definition/microsoft-security", 3},
			{"/product/ege-chemistry-courses", 3},
			{"/dictionary/definition/xml", 3},
			{"/profession/cio", 3},
			{"/profession/network-administrator", 3},
			{"/vendor/cisco/testing/1", 3},
			{"/product/visual-studio-courses", 3},
			{"/product/ege-chemistry", 3},
			{"/product/1c-upravlenie-proizvodstvennym-predpriyatiem-8-courses", 3},
			{"/vendor/lpi", 3},
			{"/product/ege-obschestvoznanie", 4},
			{"/profession/analyst", 4},
			{"/profession/скс-specialist", 4},
			{"/vendor/cryptopro", 4},
			{"/dictionary/definition/italy-drawing", 4},
			{"/vendor/embarcadero", 4},
			{"/certification/professional-ccnp", 4},
			{"/product/ege-english-courses", 4},
			{"/vendor/pmi/certifications", 4},
			{"/profession/microsoft-admin", 4},
			{"/profession/unix-admin", 4},
			{"/vendor/oracle/testing/1", 4},
			{"/product/cpp-builder-courses", 4},
			{"/vendor/aladdin", 4},
			{"/vendor/corel", 4},
			{"/dictionary/definition/italy-video", 4},
			{"/vendor/blackberry/testing/1", 4},
			{"/profession/kassir", 4},
			{"/dictionary/definition/landscape-design", 4},
			{"/product/1c-zarplata-i-kadry-77-courses", 4},
			{"/product/zbrush-courses", 4},
			{"/profession/artist", 4},
			{"/profession/office-manager", 4},
			{"/product/lync-server-2010-courses", 4},
			{"/vendor/graphisoft", 4},
			{"/product/1c-upravlenie-nebolshoi-firmoi-8-courses", 4},
			{"/dictionary/definition/webinar", 4},
			{"/product/photoshop", 4},
			{"/product/1c-buhgalteriya-77-courses", 4},
			{"/dictionary/definition/microsoft-licensing", 4},
			{"/product/forefront-courses", 4},
			{"/product/ege-math", 4},
			{"/product/freebsd-courses", 4},
			{"/product/pro-engineer-courses", 4},
			{"/dictionary/definition/mof", 4},
			{"/profession/cisco-engineer", 4},
			{"/vendor/lpi/certifications", 4},
			{"/profession/architect", 4},
			{"/product/ibmspss-courses", 4},
			{"/profession/it-manager", 4},
			{"/profession/kadr-manager", 4},
			{"/product/1cbitrix-courses", 4},
			{"/product/1c-uproschenka-8-courses", 4},
			{"/product/ege-biology-courses", 4},
			{"/profession/video-engineer", 5},
			{"/product/visual-studio-dot-net-2003-courses", 5},
			{"/vendor/comptia/certifications", 5},
			{"/product/visual-c-plus-courses", 5},
		};
	}
}