//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Specialist.Entities.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql;Initial Catalog=Tests;User ID=ptolochko;Password=saoPRY")]
        public string TestsConnectionString {
            get {
                return ((string)(this["TestsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=apz002;Initial Catalog=SPECREPL_replicating;Persist Security Info=Tru" +
            "e;User ID=IUser;Password=iamaguest")]
        public string SPECREPL_replicatingConnectionString {
            get {
                return ((string)(this["SPECREPL_replicatingConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ssz001.dev\\sqlee;Initial Catalog=Maillist;Persist Security Info=True;" +
            "User ID=iuser;Password=iamaguest")]
        public string MaillistConnectionString {
            get {
                return ((string)(this["MaillistConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=apz002;Initial Catalog=SpecialistWeb;Persist Security Info=True;User " +
            "ID=IUser;Password=iamaguest")]
        public string SpecialistWebConnectionString {
            get {
                return ((string)(this["SpecialistWebConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ssz001\\sqlee;Initial Catalog=For_SECONDARY;Persist Security Info=True" +
            ";User ID=IUser;Password=iamaguest")]
        public string For_SECONDARYConnectionString {
            get {
                return ((string)(this["For_SECONDARYConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=apz002;Initial Catalog=Passport;Persist Security Info=True;User ID=IU" +
            "ser;Password=iamaguest")]
        public string PassportConnectionString {
            get {
                return ((string)(this["PassportConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=apz002;Initial Catalog=SPECREPL_replicating;Persist Security Info=Tru" +
            "e;User ID=IUser;Password=iamaguest")]
        public string SPECIALISTConnectionString {
            get {
                return ((string)(this["SPECIALISTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=pioneer.specialist.ru;Initial Catalog=SPECIALIST;User ID=SpecWebDataE" +
            "ditor;Password=ghjdbltw;MultipleActiveResultSets=True")]
        public string PioneerConnectionString {
            get {
                return ((string)(this["PioneerConnectionString"]));
            }
        }
    }
}
