#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Specialist.Entities.Secondary
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="For_SECONDARY")]
	public partial class ForSecondaryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertQuestionAnswer(QuestionAnswer instance);
    partial void UpdateQuestionAnswer(QuestionAnswer instance);
    partial void DeleteQuestionAnswer(QuestionAnswer instance);
    partial void InsertGroupSurvey(GroupSurvey instance);
    partial void UpdateGroupSurvey(GroupSurvey instance);
    partial void DeleteGroupSurvey(GroupSurvey instance);
    #endregion
		
		public ForSecondaryDataContext() : 
				base(global::Specialist.Entities.Properties.Settings.Default.For_SECONDARYConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ForSecondaryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ForSecondaryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ForSecondaryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ForSecondaryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<QuestionAnswer> QuestionAnswers
		{
			get
			{
				return this.GetTable<QuestionAnswer>();
			}
		}
		
		public System.Data.Linq.Table<GroupSurvey> GroupSurveys
		{
			get
			{
				return this.GetTable<GroupSurvey>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="For_SECONDARY.dbo.QuestionAnswers")]
	public partial class QuestionAnswer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VoteId;
		
		private System.Nullable<int> _UserID;
		
		private System.Nullable<System.DateTime> _VoteDate;
		
		private string _Question1;
		
		private string _Question2;
		
		private string _Question3;
		
		private string _Question4;
		
		private string _Question5;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVoteIdChanging(int value);
    partial void OnVoteIdChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    partial void OnVoteDateChanging(System.Nullable<System.DateTime> value);
    partial void OnVoteDateChanged();
    partial void OnQuestion1Changing(string value);
    partial void OnQuestion1Changed();
    partial void OnQuestion2Changing(string value);
    partial void OnQuestion2Changed();
    partial void OnQuestion3Changing(string value);
    partial void OnQuestion3Changed();
    partial void OnQuestion4Changing(string value);
    partial void OnQuestion4Changed();
    partial void OnQuestion5Changing(string value);
    partial void OnQuestion5Changed();
    #endregion
		
		public QuestionAnswer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VoteId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int VoteId
		{
			get
			{
				return this._VoteId;
			}
			set
			{
				if ((this._VoteId != value))
				{
					this.OnVoteIdChanging(value);
					this.SendPropertyChanging();
					this._VoteId = value;
					this.SendPropertyChanged("VoteId");
					this.OnVoteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VoteDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> VoteDate
		{
			get
			{
				return this._VoteDate;
			}
			set
			{
				if ((this._VoteDate != value))
				{
					this.OnVoteDateChanging(value);
					this.SendPropertyChanging();
					this._VoteDate = value;
					this.SendPropertyChanged("VoteDate");
					this.OnVoteDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question1", DbType="VarChar(300)")]
		public string Question1
		{
			get
			{
				return this._Question1;
			}
			set
			{
				if ((this._Question1 != value))
				{
					this.OnQuestion1Changing(value);
					this.SendPropertyChanging();
					this._Question1 = value;
					this.SendPropertyChanged("Question1");
					this.OnQuestion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question2", DbType="VarChar(1000)")]
		public string Question2
		{
			get
			{
				return this._Question2;
			}
			set
			{
				if ((this._Question2 != value))
				{
					this.OnQuestion2Changing(value);
					this.SendPropertyChanging();
					this._Question2 = value;
					this.SendPropertyChanged("Question2");
					this.OnQuestion2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question3", DbType="VarChar(300)")]
		public string Question3
		{
			get
			{
				return this._Question3;
			}
			set
			{
				if ((this._Question3 != value))
				{
					this.OnQuestion3Changing(value);
					this.SendPropertyChanging();
					this._Question3 = value;
					this.SendPropertyChanged("Question3");
					this.OnQuestion3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question4", DbType="VarChar(1000)")]
		public string Question4
		{
			get
			{
				return this._Question4;
			}
			set
			{
				if ((this._Question4 != value))
				{
					this.OnQuestion4Changing(value);
					this.SendPropertyChanging();
					this._Question4 = value;
					this.SendPropertyChanged("Question4");
					this.OnQuestion4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question5")]
		public string Question5
		{
			get
			{
				return this._Question5;
			}
			set
			{
				if ((this._Question5 != value))
				{
					this.OnQuestion5Changing(value);
					this.SendPropertyChanging();
					this._Question5 = value;
					this.SendPropertyChanged("Question5");
					this.OnQuestion5Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="For_SECONDARY.dbo.GroupSurvey")]
	public partial class GroupSurvey : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Reply1;
		
		private string _Reply2;
		
		private System.DateTime _InputDate;
		
		private decimal _Student_ID;
		
		private decimal _Group_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnReply1Changing(string value);
    partial void OnReply1Changed();
    partial void OnReply2Changing(string value);
    partial void OnReply2Changed();
    partial void OnInputDateChanging(System.DateTime value);
    partial void OnInputDateChanged();
    partial void OnStudent_IDChanging(decimal value);
    partial void OnStudent_IDChanged();
    partial void OnGroup_IDChanging(decimal value);
    partial void OnGroup_IDChanged();
    #endregion
		
		public GroupSurvey()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reply1", DbType="VarChar(1500)")]
		public string Reply1
		{
			get
			{
				return this._Reply1;
			}
			set
			{
				if ((this._Reply1 != value))
				{
					this.OnReply1Changing(value);
					this.SendPropertyChanging();
					this._Reply1 = value;
					this.SendPropertyChanged("Reply1");
					this.OnReply1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reply2", DbType="VarChar(1500)")]
		public string Reply2
		{
			get
			{
				return this._Reply2;
			}
			set
			{
				if ((this._Reply2 != value))
				{
					this.OnReply2Changing(value);
					this.SendPropertyChanging();
					this._Reply2 = value;
					this.SendPropertyChanged("Reply2");
					this.OnReply2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputDate", DbType="SmallDateTime NOT NULL")]
		public System.DateTime InputDate
		{
			get
			{
				return this._InputDate;
			}
			set
			{
				if ((this._InputDate != value))
				{
					this.OnInputDateChanging(value);
					this.SendPropertyChanging();
					this._InputDate = value;
					this.SendPropertyChanged("InputDate");
					this.OnInputDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal Student_ID
		{
			get
			{
				return this._Student_ID;
			}
			set
			{
				if ((this._Student_ID != value))
				{
					this.OnStudent_IDChanging(value);
					this.SendPropertyChanging();
					this._Student_ID = value;
					this.SendPropertyChanged("Student_ID");
					this.OnStudent_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal Group_ID
		{
			get
			{
				return this._Group_ID;
			}
			set
			{
				if ((this._Group_ID != value))
				{
					this.OnGroup_IDChanging(value);
					this.SendPropertyChanging();
					this._Group_ID = value;
					this.SendPropertyChanged("Group_ID");
					this.OnGroup_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
