//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Specialist.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Specialist.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Best2010Icon {
            get {
                object obj = ResourceManager.GetObject("Best2010Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Best2011Icon {
            get {
                object obj = ResourceManager.GetObject("Best2011Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BestgraduateIcon {
            get {
                object obj = ResourceManager.GetObject("BestgraduateIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CardaIcon {
            get {
                object obj = ResourceManager.GetObject("CardaIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CarddIcon {
            get {
                object obj = ResourceManager.GetObject("CarddIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CardgIcon {
            get {
                object obj = ResourceManager.GetObject("CardgIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CardpIcon {
            get {
                object obj = ResourceManager.GetObject("CardpIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CardsIcon {
            get {
                object obj = ResourceManager.GetObject("CardsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q:Прикройте один глаз, затем другой. Каким глазом Вы видите лучше - правым или левым?
        ///i://cdn.specialist.ru/content/image/SimpleTest/1/glaz.jpg
        ///a:Левым
        ///a:Правым 
        ///a:Одинаково 
        ///
        ///q:Какие еще бывают корни, кроме корней деревьев? 
        ///i://cdn.specialist.ru/content/image/SimpleTest/1/derevo.png
        ///a:Корень - основная часть слова (без приставок и суффиксов) 
        ///a:Корень, который можно извлечь из числа. Вариант - корень уравнения. 
        ///a:Одновременно вспомнил/а несколько значений
        ///
        ///q:Внимательно посмотрите н [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewtonTest {
            get {
                return ResourceManager.GetString("NewtonTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r:Вы – Есенин,  гуманитарного склада, у Вас лучше развито правое полушарие мозга, Вы мыслите образно. Для того чтобы сделать умозаключение, Вам необязательно разбивать ситуацию на кусочки, анализировать и потом опять собирать все воедино, находить логику, перепроверять, строить модели. Вы охватываете ситуацию в целом, пытаетесь прочувствовать ее, а недостаток информации восполняете за счет интуиции. У Вас хорошие лингвистические способности, открытый и общительный характер. Вам язык слов и букв значительно  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewtonTestResult {
            get {
                return ResourceManager.GetString("NewtonTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Webinar2011Icon {
            get {
                object obj = ResourceManager.GetObject("Webinar2011Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegWrite, REG_SZ, HKEY_CURRENT_USER, SOFTWARE\Citrix\GoToMeeting, rememberMe, false
        ///Run, %comspec% /c &quot;&quot;%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Citrix\GoToMeeting.lnk&quot; &quot;/Action Join&quot; &quot;/Trigger Shortcut&quot; &quot;/Product G2M&quot; &quot;/FreeTrialUrl&quot;&quot;, , hide
        ///BlockInput, On
        ///WinWait, Join a session - GoToMeeting, 
        ///IfWinNotActive, Join a session - GoToMeeting, , WinActivate, Join a session - GoToMeeting, 
        ///WinWaitActive, Join a session - GoToMeeting,
        ///Sleep, 100
        ///Send, [WebinarId]{ENTER}		; ВСТ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebinarLauncherTamplate {
            get {
                return ResourceManager.GetString("WebinarLauncherTamplate", resourceCulture);
            }
        }
    }
}
